
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace DAL
{
	public abstract class _Levels : SqlClientEntity
	{
		public _Levels()
		{
			this.QuerySource = "Levels";
			this.MappingName = "Levels";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_LevelsLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int LevelID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.LevelID, LevelID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_LevelsLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter LevelID
			{
				get
				{
					return new SqlParameter("@LevelID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter LevelName
			{
				get
				{
					return new SqlParameter("@LevelName", SqlDbType.NVarChar, 300);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string LevelID = "LevelID";
            public const string LevelName = "LevelName";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[LevelID] = _Levels.PropertyNames.LevelID;
					ht[LevelName] = _Levels.PropertyNames.LevelName;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string LevelID = "LevelID";
            public const string LevelName = "LevelName";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[LevelID] = _Levels.ColumnNames.LevelID;
					ht[LevelName] = _Levels.ColumnNames.LevelName;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string LevelID = "s_LevelID";
            public const string LevelName = "s_LevelName";

		}
		#endregion		
		
		#region Properties
	
		public virtual int LevelID
	    {
			get
	        {
				return base.Getint(ColumnNames.LevelID);
			}
			set
	        {
				base.Setint(ColumnNames.LevelID, value);
			}
		}

		public virtual string LevelName
	    {
			get
	        {
				return base.Getstring(ColumnNames.LevelName);
			}
			set
	        {
				base.Setstring(ColumnNames.LevelName, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_LevelID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.LevelID) ? string.Empty : base.GetintAsString(ColumnNames.LevelID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.LevelID);
				else
					this.LevelID = base.SetintAsString(ColumnNames.LevelID, value);
			}
		}

		public virtual string s_LevelName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.LevelName) ? string.Empty : base.GetstringAsString(ColumnNames.LevelName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.LevelName);
				else
					this.LevelName = base.SetstringAsString(ColumnNames.LevelName, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter LevelID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.LevelID, Parameters.LevelID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter LevelName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.LevelName, Parameters.LevelName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter LevelID
		    {
				get
		        {
					if(_LevelID_W == null)
	        	    {
						_LevelID_W = TearOff.LevelID;
					}
					return _LevelID_W;
				}
			}

			public WhereParameter LevelName
		    {
				get
		        {
					if(_LevelName_W == null)
	        	    {
						_LevelName_W = TearOff.LevelName;
					}
					return _LevelName_W;
				}
			}

			private WhereParameter _LevelID_W = null;
			private WhereParameter _LevelName_W = null;

			public void WhereClauseReset()
			{
				_LevelID_W = null;
				_LevelName_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter LevelID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.LevelID, Parameters.LevelID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter LevelName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.LevelName, Parameters.LevelName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter LevelID
		    {
				get
		        {
					if(_LevelID_W == null)
	        	    {
						_LevelID_W = TearOff.LevelID;
					}
					return _LevelID_W;
				}
			}

			public AggregateParameter LevelName
		    {
				get
		        {
					if(_LevelName_W == null)
	        	    {
						_LevelName_W = TearOff.LevelName;
					}
					return _LevelName_W;
				}
			}

			private AggregateParameter _LevelID_W = null;
			private AggregateParameter _LevelName_W = null;

			public void AggregateClauseReset()
			{
				_LevelID_W = null;
				_LevelName_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_LevelsInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.LevelID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_LevelsUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_LevelsDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.LevelID);
			p.SourceColumn = ColumnNames.LevelID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.LevelID);
			p.SourceColumn = ColumnNames.LevelID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.LevelName);
			p.SourceColumn = ColumnNames.LevelName;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
