
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace DAL
{
	public abstract class _SportClubMembers : SqlClientEntity
	{
		public _SportClubMembers()
		{
			this.QuerySource = "SportClubMembers";
			this.MappingName = "SportClubMembers";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_SportClubMembersLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int SportClubMembersID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.SportClubMembersID, SportClubMembersID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_SportClubMembersLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter SportClubMembersID
			{
				get
				{
					return new SqlParameter("@SportClubMembersID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter MemberName
			{
				get
				{
					return new SqlParameter("@MemberName", SqlDbType.NVarChar, 300);
				}
			}
			
			public static SqlParameter MemberFitness
			{
				get
				{
					return new SqlParameter("@MemberFitness", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter MemberSpeed
			{
				get
				{
					return new SqlParameter("@MemberSpeed", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter MemberTallness
			{
				get
				{
					return new SqlParameter("@MemberTallness", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter MemberWeight
			{
				get
				{
					return new SqlParameter("@MemberWeight", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string SportClubMembersID = "SportClubMembersID";
            public const string MemberName = "MemberName";
            public const string MemberFitness = "MemberFitness";
            public const string MemberSpeed = "MemberSpeed";
            public const string MemberTallness = "MemberTallness";
            public const string MemberWeight = "MemberWeight";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[SportClubMembersID] = _SportClubMembers.PropertyNames.SportClubMembersID;
					ht[MemberName] = _SportClubMembers.PropertyNames.MemberName;
					ht[MemberFitness] = _SportClubMembers.PropertyNames.MemberFitness;
					ht[MemberSpeed] = _SportClubMembers.PropertyNames.MemberSpeed;
					ht[MemberTallness] = _SportClubMembers.PropertyNames.MemberTallness;
					ht[MemberWeight] = _SportClubMembers.PropertyNames.MemberWeight;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string SportClubMembersID = "SportClubMembersID";
            public const string MemberName = "MemberName";
            public const string MemberFitness = "MemberFitness";
            public const string MemberSpeed = "MemberSpeed";
            public const string MemberTallness = "MemberTallness";
            public const string MemberWeight = "MemberWeight";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[SportClubMembersID] = _SportClubMembers.ColumnNames.SportClubMembersID;
					ht[MemberName] = _SportClubMembers.ColumnNames.MemberName;
					ht[MemberFitness] = _SportClubMembers.ColumnNames.MemberFitness;
					ht[MemberSpeed] = _SportClubMembers.ColumnNames.MemberSpeed;
					ht[MemberTallness] = _SportClubMembers.ColumnNames.MemberTallness;
					ht[MemberWeight] = _SportClubMembers.ColumnNames.MemberWeight;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string SportClubMembersID = "s_SportClubMembersID";
            public const string MemberName = "s_MemberName";
            public const string MemberFitness = "s_MemberFitness";
            public const string MemberSpeed = "s_MemberSpeed";
            public const string MemberTallness = "s_MemberTallness";
            public const string MemberWeight = "s_MemberWeight";

		}
		#endregion		
		
		#region Properties
	
		public virtual int SportClubMembersID
	    {
			get
	        {
				return base.Getint(ColumnNames.SportClubMembersID);
			}
			set
	        {
				base.Setint(ColumnNames.SportClubMembersID, value);
			}
		}

		public virtual string MemberName
	    {
			get
	        {
				return base.Getstring(ColumnNames.MemberName);
			}
			set
	        {
				base.Setstring(ColumnNames.MemberName, value);
			}
		}

		public virtual int MemberFitness
	    {
			get
	        {
				return base.Getint(ColumnNames.MemberFitness);
			}
			set
	        {
				base.Setint(ColumnNames.MemberFitness, value);
			}
		}

		public virtual int MemberSpeed
	    {
			get
	        {
				return base.Getint(ColumnNames.MemberSpeed);
			}
			set
	        {
				base.Setint(ColumnNames.MemberSpeed, value);
			}
		}

		public virtual int MemberTallness
	    {
			get
	        {
				return base.Getint(ColumnNames.MemberTallness);
			}
			set
	        {
				base.Setint(ColumnNames.MemberTallness, value);
			}
		}

		public virtual int MemberWeight
	    {
			get
	        {
				return base.Getint(ColumnNames.MemberWeight);
			}
			set
	        {
				base.Setint(ColumnNames.MemberWeight, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_SportClubMembersID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SportClubMembersID) ? string.Empty : base.GetintAsString(ColumnNames.SportClubMembersID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SportClubMembersID);
				else
					this.SportClubMembersID = base.SetintAsString(ColumnNames.SportClubMembersID, value);
			}
		}

		public virtual string s_MemberName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.MemberName) ? string.Empty : base.GetstringAsString(ColumnNames.MemberName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.MemberName);
				else
					this.MemberName = base.SetstringAsString(ColumnNames.MemberName, value);
			}
		}

		public virtual string s_MemberFitness
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.MemberFitness) ? string.Empty : base.GetintAsString(ColumnNames.MemberFitness);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.MemberFitness);
				else
					this.MemberFitness = base.SetintAsString(ColumnNames.MemberFitness, value);
			}
		}

		public virtual string s_MemberSpeed
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.MemberSpeed) ? string.Empty : base.GetintAsString(ColumnNames.MemberSpeed);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.MemberSpeed);
				else
					this.MemberSpeed = base.SetintAsString(ColumnNames.MemberSpeed, value);
			}
		}

		public virtual string s_MemberTallness
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.MemberTallness) ? string.Empty : base.GetintAsString(ColumnNames.MemberTallness);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.MemberTallness);
				else
					this.MemberTallness = base.SetintAsString(ColumnNames.MemberTallness, value);
			}
		}

		public virtual string s_MemberWeight
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.MemberWeight) ? string.Empty : base.GetintAsString(ColumnNames.MemberWeight);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.MemberWeight);
				else
					this.MemberWeight = base.SetintAsString(ColumnNames.MemberWeight, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter SportClubMembersID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SportClubMembersID, Parameters.SportClubMembersID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter MemberName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.MemberName, Parameters.MemberName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter MemberFitness
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.MemberFitness, Parameters.MemberFitness);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter MemberSpeed
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.MemberSpeed, Parameters.MemberSpeed);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter MemberTallness
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.MemberTallness, Parameters.MemberTallness);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter MemberWeight
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.MemberWeight, Parameters.MemberWeight);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter SportClubMembersID
		    {
				get
		        {
					if(_SportClubMembersID_W == null)
	        	    {
						_SportClubMembersID_W = TearOff.SportClubMembersID;
					}
					return _SportClubMembersID_W;
				}
			}

			public WhereParameter MemberName
		    {
				get
		        {
					if(_MemberName_W == null)
	        	    {
						_MemberName_W = TearOff.MemberName;
					}
					return _MemberName_W;
				}
			}

			public WhereParameter MemberFitness
		    {
				get
		        {
					if(_MemberFitness_W == null)
	        	    {
						_MemberFitness_W = TearOff.MemberFitness;
					}
					return _MemberFitness_W;
				}
			}

			public WhereParameter MemberSpeed
		    {
				get
		        {
					if(_MemberSpeed_W == null)
	        	    {
						_MemberSpeed_W = TearOff.MemberSpeed;
					}
					return _MemberSpeed_W;
				}
			}

			public WhereParameter MemberTallness
		    {
				get
		        {
					if(_MemberTallness_W == null)
	        	    {
						_MemberTallness_W = TearOff.MemberTallness;
					}
					return _MemberTallness_W;
				}
			}

			public WhereParameter MemberWeight
		    {
				get
		        {
					if(_MemberWeight_W == null)
	        	    {
						_MemberWeight_W = TearOff.MemberWeight;
					}
					return _MemberWeight_W;
				}
			}

			private WhereParameter _SportClubMembersID_W = null;
			private WhereParameter _MemberName_W = null;
			private WhereParameter _MemberFitness_W = null;
			private WhereParameter _MemberSpeed_W = null;
			private WhereParameter _MemberTallness_W = null;
			private WhereParameter _MemberWeight_W = null;

			public void WhereClauseReset()
			{
				_SportClubMembersID_W = null;
				_MemberName_W = null;
				_MemberFitness_W = null;
				_MemberSpeed_W = null;
				_MemberTallness_W = null;
				_MemberWeight_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter SportClubMembersID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SportClubMembersID, Parameters.SportClubMembersID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter MemberName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.MemberName, Parameters.MemberName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter MemberFitness
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.MemberFitness, Parameters.MemberFitness);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter MemberSpeed
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.MemberSpeed, Parameters.MemberSpeed);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter MemberTallness
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.MemberTallness, Parameters.MemberTallness);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter MemberWeight
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.MemberWeight, Parameters.MemberWeight);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter SportClubMembersID
		    {
				get
		        {
					if(_SportClubMembersID_W == null)
	        	    {
						_SportClubMembersID_W = TearOff.SportClubMembersID;
					}
					return _SportClubMembersID_W;
				}
			}

			public AggregateParameter MemberName
		    {
				get
		        {
					if(_MemberName_W == null)
	        	    {
						_MemberName_W = TearOff.MemberName;
					}
					return _MemberName_W;
				}
			}

			public AggregateParameter MemberFitness
		    {
				get
		        {
					if(_MemberFitness_W == null)
	        	    {
						_MemberFitness_W = TearOff.MemberFitness;
					}
					return _MemberFitness_W;
				}
			}

			public AggregateParameter MemberSpeed
		    {
				get
		        {
					if(_MemberSpeed_W == null)
	        	    {
						_MemberSpeed_W = TearOff.MemberSpeed;
					}
					return _MemberSpeed_W;
				}
			}

			public AggregateParameter MemberTallness
		    {
				get
		        {
					if(_MemberTallness_W == null)
	        	    {
						_MemberTallness_W = TearOff.MemberTallness;
					}
					return _MemberTallness_W;
				}
			}

			public AggregateParameter MemberWeight
		    {
				get
		        {
					if(_MemberWeight_W == null)
	        	    {
						_MemberWeight_W = TearOff.MemberWeight;
					}
					return _MemberWeight_W;
				}
			}

			private AggregateParameter _SportClubMembersID_W = null;
			private AggregateParameter _MemberName_W = null;
			private AggregateParameter _MemberFitness_W = null;
			private AggregateParameter _MemberSpeed_W = null;
			private AggregateParameter _MemberTallness_W = null;
			private AggregateParameter _MemberWeight_W = null;

			public void AggregateClauseReset()
			{
				_SportClubMembersID_W = null;
				_MemberName_W = null;
				_MemberFitness_W = null;
				_MemberSpeed_W = null;
				_MemberTallness_W = null;
				_MemberWeight_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_SportClubMembersInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.SportClubMembersID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_SportClubMembersUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_SportClubMembersDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.SportClubMembersID);
			p.SourceColumn = ColumnNames.SportClubMembersID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.SportClubMembersID);
			p.SourceColumn = ColumnNames.SportClubMembersID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.MemberName);
			p.SourceColumn = ColumnNames.MemberName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.MemberFitness);
			p.SourceColumn = ColumnNames.MemberFitness;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.MemberSpeed);
			p.SourceColumn = ColumnNames.MemberSpeed;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.MemberTallness);
			p.SourceColumn = ColumnNames.MemberTallness;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.MemberWeight);
			p.SourceColumn = ColumnNames.MemberWeight;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
